language: rust
cache: false

rust:
  - stable
  - beta
  - nightly

stages:
  - build
  - test


jobs:
  include:
    - stage: build
      script: cargo build --verbose
    - stage: test
      script: cargo test --verbose
