language: rust

matrix:
  include:
     - rust: stable
      script:
        - cargo build

     - rust: beta
      script:
        - cargo build

    - rust: nightly
      script:
        - cargo build
        - cargo test
