language: rust
# comment


before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

matrix:
  include:
    - os: osx
      rust: stable
      script:
        - cargo build

    - os: linux
      rust: beta
      script:
        - cargo build

    - os: linux
      rust: nightly
      script:
        - cargo build
        - cargo test

