matrix:
  include:
    - language: rust
      rust:
        - stable
      script:
        - cargo build

    - language: rust
      rust:
        - nightly
      script:
        - cargo build
        - cargo test
