language: rust
cache: false

jobs:
  - language: rust
      rust: stable
      before_script:
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check

      script:
        - cargo build --verbose
        - cargo test --verbose

  - language: rust
      rust: beta
      before_script:
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check

      script:
        - cargo build --verbose
        - cargo test --verbose


  - language: rust
      rust: nightly
      before_script:
        - rustup component add rustfmt-preview
        - cargo fmt --all -- --check

      script:
        - cargo build --verbose
        - cargo test --verbose
