language: rust

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

matrix:
  include:
    - rust: stable
      script:
        - cargo build

    - rust: beta
      script:
        - cargo build

    - rust: nightly
      script:
        - cargo build
        - cargo test

