language: rust
cache: false

rust:
  - stable
  - beta
  - nightly

stages:
  - build
  - name: test
    if: rust = nightly

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

jobs:
  include:
    - stage: build
      script: cargo build --verbose
    - stage: test
      script: cargo test --verbose
