language: rust
cache: false


before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

jobs:
  - language: rust
    rust: stable

    script:
      - cargo build --verbose

  - language: rust
    rust: beta

    script:
      - cargo build --verbose

  - language: rust
    rust: nightly

    script:
      - cargo build --verbose
      - cargo test --verbose
